---
- name: test play
  hosts: webservers
  serial:
    - 1
    - 2
    - 5
  gather_facts: False

  tasks:
    - name: first task
      command: hostname
    - name: second task
      command: hostname