---
- name: test play
  hosts: webservers
  serial: 2
#  serial: "30%" - 30 percentage hosts will be executed together
  gather_facts: False

  tasks:
    - name: first task
      command: hostname
    - name: second task
      command: hostname
      
