---
- hosts: ubuntu
  become: true
  tasks:
      - name: "apt-get update"
        apt:
         update_cache: yes
         cache_valid_time: 3600

      - name: Install nginx web server
        apt: name=nginx state=latest
        notify:
          - start nginx

      - name: Upload the default index.html file
        copy: src=index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
      - name: start nginx
        service: name=nginx state=restarted