- name: Retrieve hostname
#hosts can be group or host alias or a combination as given below
  hosts:
    - ubuntu1
    - centos
  tasks:
    - name: Retrieve the hostname
      command: hostname
      register: result
    - debug:
        var: result