- name: Retrieve hostname
  hosts:
    - localhost
  tasks:
    - name: Retrieve the hostname
      command: hostname
      register: result
    - set_fact:
        hostname1: "{{ result.stdout }}"
    - debug:
        var: hostname1
        
#set_facts allows us to set facts
#https://docs.ansible.com/ansible/2.9/modules/set_fact_module.html#examples        