  tasks:
   - name: Install, configure, and start Apache
     block:
       - name: Install httpd and memcached
         ansible.builtin.yum:
           name:
           - httpd
           - memcached
           state: present

#       - name: Apply the foo config template
#         ansible.builtin.template:
#           src: templates/src.j2
#           dest: /etc/foo.conf

       - name: Start service apache and memcached and enable it
         ansible.builtin.service:
           name: 
           - httpd
           - memcached
           state: started
           enabled: True
     when: ansible_facts['distribution'] == 'CentOS'
     become: true
     become_user: root
     ignore_errors: yes
	 
#when above will be evaluated 
#    before ansible runs each of the three tasks.	 
#Each tasks also inherits
#   become
#   ignore_errors