#Reference: https://github.com/mdklatt/ansible-python3-role

---
- name: install Docker
  hosts: centos
  become: true
  tasks:
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started
        
#    - name: Install Docker-Compose
#      yum:
#        name: docker-compose

    - name: Install python latest module
      yum:
        name: 
          - python-setuptools
          - python3
          - python3-devel
          - python3-pip        
        state: latest
        
    - name: Install Python docker compose
      pip:
        name: 
#        - docker-compose
        - docker
        - requests
        - virtualenv
      state: present
      executable: pip3