---
- name: install Google Chrome
  hosts: windows
  become: false
  gather_facts: false
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: present