---
- name: Install and configure Apache web server
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache package
      package:
        name: "{{ apache_package }}"
        state: present
      vars:
        apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

    - name: Ensure Apache is started and enabled
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
      vars:
        apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

    - name: Allow HTTP and HTTPS through the firewall (Debian)
      ufw:
        rule: allow
        name: "{{ item }}"
      with_items:
        - 'Apache'
        - 'Apache Secure'
      when: ansible_os_family == "Debian"

    - name: Open HTTP and HTTPS ports on firewall (CentOS)
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - http
        - https
      when: ansible_os_family == "RedHat"

    - name: Test Apache by fetching the default page
      uri:
        url: "http://localhost"
        method: GET
        status_code: 200
      register: result

    - debug:
        msg: "{{ result }}"
