---
- name: Install PHP 8.0 and required extensions on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Add Ondřej Surý PPA repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install PHP 8.0 and extensions
      apt:
        name:
          - php8.0
          - php8.0-cli
          - php8.0-common
          - php8.0-fpm
          - php8.0-mysql
          - php8.0-gd
          - php8.0-mbstring
          - php8.0-curl
          - php8.0-xml
        state: present

    - name: Ensure PHP-FPM is started and enabled
      service:
        name: php8.0-fpm
        state: started
        enabled: yes

