- name: list installed and available versions of ruby
  yum:
    list: ruby
  become: true
  when: ansible_os_family == 'CentOS'
  register: yum_output

- name: print available ruby versions
  debug:#debug task will print message below
    msg: "{{ item.version }}-{{ item.release }}"
  loop: "{{ yum_output.results | selectattr('yumstate', 'equalto', 'available') | list }}"

- debug: var=yum_output
#debug task will print the full contents of yum_output