---
- hosts: crunchify
  become: yes
 
  pre_tasks:
     - raw: sudo apt-get -y install python-simplejson
       register: py_simple_output
     - raw: sudo apt-get -y install python-minimal
       register: py_minimal_output
     - raw: sudo apt-get update
       register: system_output
     - raw: sudo apt-get install -y default-jre
       register: java_output
 
  tasks:
  
    - name: get Java version
      shell: java --version 2>&1