---
- name: Install PyMySQL on all servers
  hosts: all
  become: true
  tasks:
    - name: Install pip3
      package:
        name: python3-pip
        state: present

    - name: Install PyMySQL using pip3
      pip:
        name: PyMySQL
        state: present
        executable: pip3
