---
- name: Set up Linux package repositories and update
  hosts: webservers
  become: true

  tasks:
    - name: Update apt package list (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update yum package list (RedHat)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install required packages (Debian)
      apt:
        name:
          - curl
          - wget
          - git
          - vim
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat)
      yum:
        name:
          - curl
          - wget
          - git
          - vim
        state: present
      when: ansible_os_family == "RedHat"
