---
- name: Install python in target node with ansible
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: copy upgrade-python code
    copy:
      src: /home/vilas/tmp/upgrade-python.sh
      dest: /home/vilas/upgrade-python.sh
      owner: vilas
      group: vilas
      mode: u=rwx,g=r,o=r
  - name: install python
    raw: 'cat < /home/vilas/upgrade-python.sh'
    args:
      executable: /bin/bash
    register: upgrade_result
  - name: debug result
    debug:
      msg: "{{ upgrade_result }}"