---
- name: Install python in target node with ansible
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: copy upgrade-python code
    copy:
      src: /home/abhirami/ansible/05playbook/upgrade-python.sh
      dest: /home/abhirami/upgrade-python.sh
      owner: abhirami
      group: abhirami
      mode: u=rwx,g=r,o=r
  - name: install python
    raw: 'cat < /home/abhirami/upgrade-python.sh'
    args:
      executable: /bin/bash
    register: upgrade_result
  - name: debug result
    debug:
      msg: "{{ upgrade_result }}"
