# cat dictvariable.yaml
---
- hosts: all
  vars:
    training:
      topic: ansible
      trainer: vilas
      lab: aws
  tasks:
  - name: print dict variable
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"
#the items can be also referred to as training.topic, training['topic']
#Refer https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#creating-valid-variable-names
#Section Referencing key:value dictionary variables
    
- hosts: all
  vars:
    training:
      topic: ansible
      trainer: vilas
      lab: aws
  tasks:
  - name: print dict variable
    debug:
      msg: "key is {{ training['topic'] }} and value is {{ training.trainer }}"