- hosts: all

  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: vilas
        group: vilas        
        mode: 0777
      with_items:
        - { src: 'foo', dest: '/usr/bin/foo' }
        - { src: 'bar', dest: '/usr/bin/bar' }
        
        
    - name: Run a shell command and register its output as a variable
      ansible.builtin.shell: /usr/bin/foo
      register: foo_result
      ignore_errors: true

    - name: Run a shell command using output of the previous task
      ansible.builtin.shell: /usr/bin/bar
      when: foo_result.rc == 0