---
- name: Install Mysql
  hosts: database
  remote_user: vagrant
  become: yes
  
  vars:
    root_db_user: root
    root_db_password: mysql
    dbname: classicmodels
    db_host: "172.42.42.102"
    
    

  tasks:

      - name: Mysql repo download
        get_url:
            url: "http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm"
            dest: /tmp
            force: yes

      - name: Install MySQL community repo
        command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm
     
  
      - name: Install DB
        yum: 
            name: mysql-server
            state: present

      - name: Install Mysql Python module
        yum:
            name: MySQL-python
            state: present

      - name: Start Mysql service and enable it
        service:
            name: mysqld
            state: started
            enabled: yes 

           
      - name: Creating database
        mysql_db: 
            name: "{{dbname}}" 
            state: present
            login_host: "{{ db_host}}"
            login_user: "{{ root_db_user }}"
            login_password: "{{ root_db_password }}"
            login_unix_socket: /var/lib/mysql/mysql.sock 

      - name: Create db User
        mysql_user: 
            name: "{{root_db_user}}"
            password: "{{root_db_password}}"
            priv: "*.*:ALL"
            host: "{{ db_host}}" 
            state: present 
            login_user: "{{ root_db_user }}" 
            login_password: "{{root_db_password}}"
       

      - name: Copy the SQL file
        copy: src=./data.sql dest=/tmp/data.sql


      - name: Run the script to populate the tables
        shell: mysql -u root -pmysql classicmodels < /tmp/data.sql



...

