- hosts: all
  tasks:
  - name: Ansible loop with index example
    debug:
      msg: "echo loop index at {{ item.0 + 1}} and value at {{item.1}}"     #note the addition here.
    with_indexed_items:
      - "hello1"
      - "hello2"
      - "hello3"