# ./database.yaml

- import_playbook: common_roles.yaml

- import_playbook: staging_roles.yaml
  when: env == 'staging'

- name: configure database servers
  hosts: "{{ env }}_database"
  roles:
    - postgres