- name: Install Apache

 apt:

  name: apache2

  state: present

  update_cache: yes



- name: Deploy custom homepage

 template:

  src: index.html.j2

  dest: /var/www/html/index.html

 when: env == "staging"

 notify: Restart Apache



- name: Start and enable Apache

 service:

  name: apache2

  state: started

  enabled: yes


