---
- name: testing
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - var_file.yml
  tasks:
    - debug:
        var: "{{ item }}.first"
      with_items: "{{ var1 }}"
      
#ansible-playbook h.yml -e  '{"var1":"loc2"}' -vv    