---
# ./redis.yml

- name: print redis package
  hosts: localhost
  tasks:
    - include_vars: vars/vars-CentOS.yml
      when: ansible_os_family == 'RedHat'
      #ansible localhost -m gather_facts | grep ansible_os_family

    - include_vars: vars/vars-Ubuntu.yml
      when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'  

    - debug: var=redis_package